version: '3'

services:
  redis:
    hostname: redis:5.0-alpine
    image: redis:alpine
    ports:
      - 6379:6379

  asyncpage:
    image: asyncpage_image
    build:
      context: backend
      dockerfile: Dockerfile
    hostname: asyncpage
    ports:
      - 8191:8191
    volumes:
      - './:/app/:rw'
    links:
      - redis
    depends_on:
      - redis

  worker:
    image: asyncpage_image
    hostname: worker
    command: rq worker --url redis://redis:6379

    depends_on:
      - redis
      - asyncpage
    links:
      - redis
      - asyncpage
